- name: install packages
  host: mongodb
  become: yes
  task:
  - name: install package
    ansible.builtin.yum:
      name: "{{item}}"
      state: installed
      # list of string
    loop:
    - nginx
    - postfix
    - cyrus-sasl-plain
    - mailx
















